"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = StepCard;
var jsx_runtime_1 = require("react/jsx-runtime");
// src/widgets/StepCard.tsx
var framer_motion_1 = require("framer-motion");
function StepCard(_a) {
    var step = _a.step, title = _a.title, desc = _a.desc, icon = _a.icon, _b = _a.accent, accent = _b === void 0 ? "from-emerald-500 to-teal-400" : _b, isLast = _a.isLast;
    return ((0, jsx_runtime_1.jsxs)(framer_motion_1.motion.div, { whileHover: { y: -3 }, className: "\n    rounded-xl relative\n    bg-white shadow-md p-6 transition hover:shadow-xl \n    dark:bg-slate-900 dark:border dark:border-emerald-900/40 dark:shadow-slate-800/50\n   \"}\n  ", children: [(0, jsx_runtime_1.jsx)("div", { className: "\r\n      mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full \r\n      bg-emerald-100 text-emerald-700 \r\n      dark:bg-emerald-500/10 dark:text-emerald-300\r\n    ", children: (0, jsx_runtime_1.jsx)("span", { className: "text-2xl font-bold", children: step }) }), (0, jsx_runtime_1.jsxs)("div", { className: "mb-2 flex items-center justify-center gap-4", children: [(0, jsx_runtime_1.jsx)("div", { className: "grid h-9 w-9 place-items-center rounded-lg bg-gradient-to-br ".concat(accent, " text-white shadow"), children: icon }), (0, jsx_runtime_1.jsx)("h3", { className: "text-lg font-semibold text-emerald-900 dark:text-emerald-200", children: title })] }), (0, jsx_runtime_1.jsx)("p", { className: "mt-2 text-center text-emerald-800/80 dark:text-slate-300/80", children: desc }), !isLast && ((0, jsx_runtime_1.jsx)("div", { className: "pointer-events-none absolute right-[-18px] top-1/2 hidden -translate-y-1/2 md:block", children: (0, jsx_runtime_1.jsx)("svg", { width: "40", height: "40", viewBox: "0 0 24 24", className: "opacity-60 dark:opacity-70", children: (0, jsx_runtime_1.jsx)("path", { d: "M5 12h12m0 0l-4-4m4 4l-4 4", fill: "none", stroke: "currentColor", strokeWidth: "2", className: "text-emerald-500 dark:text-slate-400" }) }) }))] }));
}
